---
development:
  cloud_name: duc-hoang-minh
  api_key: '919324227276873'
  api_secret: Xm-f31hlJOeUuAyvDv0zxCvALac
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: duc-hoang-minh
  api_key: '919324227276873'
  api_secret: Xm-f31hlJOeUuAyvDv0zxCvALac
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: duc-hoang-minh
  api_key: '919324227276873'
  api_secret: Xm-f31hlJOeUuAyvDv0zxCvALac
  enhance_image_tag: true
  static_image_support: false
